USE master;
GO

IF DB_ID(N'PaymentProjectDW') IS NULL
BEGIN
    EXEC(N'CREATE DATABASE PaymentProjectDW;');
END;
GO

USE PaymentProjectDW;
GO

IF SCHEMA_ID(N'dw') IS NULL
    EXEC(N'CREATE SCHEMA dw AUTHORIZATION dbo;');
GO

IF SCHEMA_ID(N'report') IS NULL
    EXEC(N'CREATE SCHEMA report AUTHORIZATION dbo;');
GO

IF SCHEMA_ID(N'stg') IS NULL
    EXEC(N'CREATE SCHEMA stg AUTHORIZATION dbo;');
GO

IF SCHEMA_ID(N'etl') IS NULL
    EXEC(N'CREATE SCHEMA etl AUTHORIZATION dbo;');
GO
